### ISSUE TITLE
What is the realm?? And Unauthorized.

### ISSUE THREAD

**Issue by jojonarte** [datso/react-native-pjsip#1]
I've tried using it, with my correct credentials that worked on CSipsimple example on native android but using your library does give me 'Unauthorized authentication'.

**Comment by datso** [comment]
Hi, Realm is used in SIP authorization, usually it is the same as host.

Try to register on our test server:
host - demo.carusto.net
realm - demo.carusto.net
username - 1000
password - test

Dial "echo" for echo test.

**Comment by jojonarte** [comment]
The test seems fine, but when registering with a different host and realm it seems to fallback to the default set 192.168.1.250 which results to getting bad authorization on other addresses.

**Comment by datso** [comment]
I found that 192.168.1.250 hardcoded inside makeCall function (pjsip-app). Regarding authorization it should work. Can you provide logs from "adb logcat" ?

**Comment by jojonarte** [comment]
My bad I was referring to the app which is a different repo, I'll just try to make a different RN app now and apply this and get back. :)
