### ISSUE TITLE
Fail to compile

### ISSUE THREAD

**Issue by iclems** [datso/react-native-pjsip#10]
Thanks again for this amazing project. It's working beautifully. For some reason, my Xcode won't compile now directly and keeps failing with the following error when building with Xcode. I've been looking at it but can't find the origin yet. I also had to disable bitcode. 
<img width="775" alt="screen shot 2017-03-03 at 7 43 21 pm" src="https://cloud.githubusercontent.com/assets/1120050/23564132/b9767b40-0049-11e7-80d4-acbc976a7706.png">

**Comment by datso** [comment]
Hi, are you trying to build with release scheme ?

**Comment by iclems** [comment]
Yes - Would that be the cause? I'm trying in debug. It could explain why it's working with react-native command line.

**Comment by datso** [comment]
Let me know whether it works in debug. Is demo app working ?

3 Мар 2017 г. 20:49 пользователь "Clément Wehrung" <notifications@github.com>
написал:

**Comment by iclems** [comment]
Looks like it's working in debug. I'll keep you posted when I get to do a final test. Is this expected?

**Comment by datso** [comment]
Probably the problem is with "build for achs" option, as I understood you
tried to build release for emulator, did you tried build for real device on
release scheme ?

3 Мар 2017 г. 20:57 пользователь "Clément Wehrung" <notifications@github.com>
написал:

**Comment by iclems** [comment]
The issue is indeed the the build setting for RTCPjSip for Release is not set to build for all archs.

**Comment by iclems** [comment]
Any reason why the build for archs shouldn't be changed for Release on master?

**Comment by datso** [comment]
I've made commit that disables ONLY_ACTIVE_ARCH, so this issue should be solved (bdda26b6776352114f3bcf6389699614b89c38bc).

**Comment by iclems** [comment]
Perfect!
