### ISSUE TITLE
Build is failing on iPhone 6S device, meanwhile works on emulator.

### ISSUE THREAD

**Issue by neyaoz** [datso/react-native-pjsip#102]
> ld: '/Users/macOS/Library/Developer/Xcode/DerivedData/App-clrxcicgbrnupufwzvtvzwrwnlcw/Build/Products/Debug-iphoneos/libRTCPjSip.a(PjSipEndpoint.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/macOS/Library/Developer/Xcode/DerivedData/App-clrxcicgbrnupufwzvtvzwrwnlcw/Build/Products/Debug-iphoneos/libRTCPjSip.a' for architecture arm64

> clang: error: linker command failed with exit code 1 (use -v to see invocation)

@datso May you help me, please?

**Comment by rcorrie** [comment]
Have you tried 

> disable bitcode for this target
