### ISSUE TITLE
App crashes when I run makeCall with headers (only iOS)

### ISSUE THREAD

**Issue by max-konin** [datso/react-native-pjsip#114]
Hello. I faced out with an issue only on iOS devices.I try to pass header with unique identificator to makeCall method. 

```javascript
const call = endpoint.makeCall(account, destination);
```
**OK**

----

```javascript
const messageOptions = { headers: { 'yid': '1' }};
const call = endpoint.makeCall(account, destination, null, messageOptions);
```
**OK**

----

```javascript
const messageOptions = { headers: { 'yid': '5b3365b394fa0000238a05c3' }};
const call = endpoint.makeCall(account, destination, null, messageOptions);
```
**Crash in random native code like this ![image](https://user-images.githubusercontent.com/1570356/41969405-7eee6fba-7a31-11e8-8418-7f62c576799c.png)**
This does not always happen. approximately in one of two cases

Android works fine...

**Comment by johnfree02** [comment]
I have some experiences about this.

Don't try to generate long text headers -> It will crash ios app or make bottlenek in app ( Animation will get stuck )

So i use just fews character with header, it works stable

**Comment by max-konin** [comment]
@johnfree02 but what if we pass a unique identifier? It can not be short

**Comment by johnfree02** [comment]
@max-konin do you need to make unique header Or Do you have your server side Not Asterisk or PBK . You can send request to server .

Becase if you sent message with headers, sip will not stable

**Comment by max-konin** [comment]
@johnfree02 The uniq ID is generated in our server side (not SIP server) and we should pass it to SIP call. May be there is opportunity to set up custom SIP id in pjsip. That would solve our problem

**Comment by anhtukhtn** [comment]
I make call with header work properly
`endpoint.makeCall(account, destination, { audioCount: 1, videoCount: 0 }, options);`

**Comment by mehdinourollah** [comment]
> I make call with header work properly `endpoint.makeCall(account, destination, { audioCount: 1, videoCount: 0 }, options);`

I love you man ❤️
