### ISSUE TITLE
Using other port than 5060

### ISSUE THREAD

**Issue by cmendes0101** [datso/react-native-pjsip#132]
I'm changing servers to not use 5060. Registration works fine but when placing it call it fails.
It's attempting to place the call to the correct domain but not including the port.

It looks like during the _normalize() the port is stripped off if using account.getDomain(): https://github.com/datso/react-native-pjsip/blob/master/src/Endpoint.js#L680

Does leaving the port cause issues on the other uses of normalize? 

My devices do register and shows "status: 'OK'" on registration object with the call attempt. Not sure why account.getRegServer() is not returning but I'll look at that separately.

**Comment by elburu** [comment]
Hello @cmendes0101, I have the same issue here, do you found any solution

**Comment by cmendes0101** [comment]
I remember I just manually modified the library to do what I needed and it worked fine.

Honestly can't remember and the project using this is no longer active. Per some random commit names, this may have been it: https://github.com/cmendes0101/react-native-pjsip/commit/2dba65b727cc71375fe4a95cfd405b7899d4b777

**Comment by elburu** [comment]
thanks, I will check it

**Comment by DrSchmurge** [comment]
i configured settings in this way ( imagine that 192.168.0.1 is my sip server address, and port is 12345) :

         {"domain": "192.168.0.1",
         "proxy": "sip:192.168.0.1:12345",
         "transport": "UDP",
         "regServer": null,
         "regTimeout": null
        }
and it works

**Comment by elburu** [comment]
@DrSchmurge thank you
