### ISSUE TITLE
[Android] Updating targetSdkVersion to 26 crashes the app

### ISSUE THREAD

**Issue by enisit** [datso/react-native-pjsip#150]
Google Play does not allow to submit applications with targetSdkVersiong lower than 26, so I had to update it to 26 but after successful build app crashes in runtime. App works fine after installation but after some time spent in sleep mode, when user try to open application, Android fails to get PjSipService back and app just crashes. Any help would be great.

**Comment by cmendes0101** [comment]
Did this occur before updating to target sdk of 26?

**Comment by enisit** [comment]
No, when I change target sdk back to 23 it works fine. Also I noticed that this problem occurs only on Android 8.0, I tested it on Android 7 and 6 and it works fine with target sdk 23 and 26. It may have something to do with garbage collection, because when you open app frequently it works fine, but after some time in background, it crashes when i try to register/create account when app opens it just crashes.

**Comment by enisit** [comment]
After spending a lot of time on debugging, I found out that starting with API 26, Android will kill services running in background after 60 seconds, except services like FCM an a few more. So Android will call onDestroy method in PjSipService when app goes in background. Problem was that endpoint instance was not destroyed properly and when the app goes back to foreground it just crashes. To solve this you need to add mEndpoint.delete() in onDestroy() method.

```
 @Override
    public void onDestroy() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
            mWorkerThread.quitSafely();
        }
        try {
            if (mEndpoint != null) {
                mEndpoint.libDestroy();
                mEndpoint.delete(); // Add this line 
            }
        } catch (Exception e) {
            Log.w(TAG, "Failed to destroy PjSip library", e);
        }

        super.onDestroy();
    }
```
