### ISSUE TITLE
Bug: yarn add/ npm install is failing more  80% of time

### ISSUE THREAD

**Issue by krajay015** [datso/react-native-pjsip#158]
I'm struggling in installing react-native-pjsip, most of the time it's taking time. I'm attaching screenshot of my terminal
**with `yarn add react-native-pjsip`**
![screenshot 2018-12-16 at 9 23 25 pm__01](https://user-images.githubusercontent.com/42569534/50055974-db198a00-017b-11e9-9e38-1fdf2e190cdf.png)

**with: `npm install --save react-native-pjsip`**
![screenshot 2018-12-16 at 9 23 48 pm__01](https://user-images.githubusercontent.com/42569534/50055982-e10f6b00-017b-11e9-8be3-a17822bc2dd1.png)

again I get an error with:
`curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github-production-release-asset-2e65be.s3.amazonaws.com:443
`

**Comment by cmendes0101** [comment]
It's possible that the release gz file that is downloaded during install is hitting a timeout. I sometimes get this on slow internet. It's about 73mb or so

I don't remember if at that point your node_modules for react-native-pjsip file exists when this happens but what you can do is manually download the file, create the lock file and then when you install(or update) it will skip the download via wget. 
The steps to follow are line 27: https://github.com/datso/react-native-pjsip/blob/master/libs.sh#L27.
