### ISSUE TITLE
undefined is not an object (account.getRegServer)

### ISSUE THREAD

**Issue by joshuaday98** [datso/react-native-pjsip#16]
![error](https://cloud.githubusercontent.com/assets/17974399/26744633/95fa7ac4-479b-11e7-8b9c-f54b1661b467.PNG)

I am receiving this error after linking the react-native-pjsip and unlinking it multiple times, I'm not sure how to fix this issue. Any help would be appreciated! Ill put the code that is using pjsip below.

    import {Endpoint} from 'react-native-pjsip';

    // Init PJSIP
    let endpoint = new Endpoint();
    let state = endpoint.start();
    let {accounts, calls} = state;
    let configuration = {proxy: null};
    let account;

    
    createSipAcc () {
    let userConfig = this.state.user.config;

    configuration.name = userConfig.sip_name;
    configuration.username = userConfig.sip_user;
    configuration.domain = userConfig.sip_domain;
    configuration.password = userConfig.sip_password;

    endpoint.createAccount(configuration)
      .then((returnAcc) => {
        console.log(returnAcc);
        account = returnAcc;
      });
    }

**Comment by datso** [comment]
Hi, seems you trying to make a call, but the account is empty. Async/await could fix the problem or use promise chains to solve this. 

As I see the problem with your code where you trying to execute `makeCall` function.

**Comment by joshuaday98** [comment]
Thank you! I was able to fix that error. Now it is getting stuck on `endpoint.createAccount()`. That one I will have to continue trying to figure out on my own. Thank you again!
