### ISSUE TITLE
Android: handle push-notification if app is close 

### ISSUE THREAD

**Issue by krajay015** [datso/react-native-pjsip#162]
In iOS we already have [react-native-callkit](https://www.npmjs.com/package/react-native-callkit) and [react-native-voip-push-notification](https://www.npmjs.com/package/react-native-voip-push-notification) to handle VoIP call. There was one [article](https://belka.us/en/callkit-android-react-native/) to create callKit for android-device but not properly explained as well as deprecated method. Can anyone help me to handle notification if App is killed in android.
PS: I'm using [react-native-push-notification](https://github.com/zo0r/react-native-push-notification/) to handle notification

@cmendes0101 ?

**Comment by krajay015** [comment]
@datso @akolpakov is there any available method to handle notification for android?

**Comment by ryanmcclure4** [comment]
Hey @krajay015 were you able to get this working?

**Comment by ryanmcclure4** [comment]
I've written a package to handle this for Android. As of now, it is very basic and simply opens the app and triggers a js callback: https://github.com/reachifyio/react-native-voip-push-receiver
