### ISSUE TITLE
How to set endpt.disable_tcp_switch configuration ?

### ISSUE THREAD

**Issue by KiPSOFT** [datso/react-native-pjsip#188]
Hi,

I getting UDP size exceed error and need disable tcp switch setting. How to set endpt.disable_tcp_switch configuration ?

https://trac.pjsip.org/repos/wiki/Using_SIP_TCP#switch

**Comment by KiPSOFT** [comment]
We added compile time define and compile this repository https://github.com/datso/react-native-pjsip-builder 

Added PJSIP_DONT_SWITCH_TO_TCP define in this file https://github.com/datso/react-native-pjsip-builder/blob/master/android/build_pjsip.sh

**Comment by rohitvc** [comment]
@KiPSOFT, @datso  we added `PJSIP_DONT_SWITCH_TO_TCP` in [build_pjsip.sh](https://github.com/rohitvc/react-native-pjsip-builder/blob/master/android/build_pjsip.sh#L18-L19) file 

Build a new `release.tar.gz` but still we are seeing the following error.

```
endpoint  ....Request msg INVITE/cseq=27756 (tdta0x70b237f0a8) exceeds UDP size threshold (1300), sending with TCP
Temporary failure in sending Request msg INVITE/cseq=27756 (tdta0x70b237f0a8), will try next server: Unsuitable transport selected (PJSIP_ETPNOTSUITABLE)
```

Anything here?
