### ISSUE TITLE
Get Error  endpoint.createAccont is not a function

### ISSUE THREAD

**Issue by amen160** [datso/react-native-pjsip#217]
Hi every body!
Can you help me.
I get error
[TypeError: endpoint.createAccont is not a function. (In 'endpoint.createAccont()', 'endpoint.createAccont' is undefined)]

mycode: 
let endpoint = new Endpoint();
let account = await endpoint.createAccont();

**Comment by amen160** [comment]
[TypeError: null is not an object (evaluating '_reactNative.NativeModules.PjSipModule.createAccount')]

**Comment by amen160** [comment]
I try  react-native link react-native-pjsip
anh get error ftom xcode
<img width="1250" alt="Screen Shot 2020-09-30 at 12 45 37" src="https://user-images.githubusercontent.com/6201829/94647554-e58a2100-031a-11eb-9ba4-54bb83a1b626.png">

**Comment by saikiran402** [comment]
Hi amen160 did you figure this out ?
