### ISSUE TITLE
hangupCall

### ISSUE THREAD

**Issue by hungtn** [datso/react-native-pjsip#23]
hi,
I have the problem.When I called hangupCall(call), the log is hangup success but it also tries to call.
how can I fix that?

**Comment by hungtn** [comment]
I found that the problem happened when transport is "UDP"

**Comment by datso** [comment]
Hi, on Android or iOS ?

**Comment by hungtn** [comment]
on iOS

**Comment by murugancmi** [comment]
Facing same issue is there any way i can fix this issue ?

**Comment by datso** [comment]
This issue caused by retransmits on UDP protocol. Please attach a tcpdump from server/client for further investigation.

**Comment by liu1083947028** [comment]
Facing same issue. When the caller hangup ,the callee app will crass. 

![Uploading image.png…]()

**Comment by omar-othmann** [comment]
@datso Sorry. I thought it was for Android

**Comment by liu1083947028** [comment]
![image](https://user-images.githubusercontent.com/7359403/35546986-7bbfe50c-05b1-11e8-8bf9-5e3c24183735.png)

it is ok.

**Comment by datso** [comment]
Please re-open the ticket once you have a reproduce with the latest version (2.7.4).
