### ISSUE TITLE
PJSIP Works On UDP But Not TCP

### ISSUE THREAD

**Issue by telecmi** [datso/react-native-pjsip#32]
When i try to use TCP i am getting (PJSIP_ETPNOTSUITABLE), If i use UDP then i can able to  register with my sip server , But when i make a call to other sip, i can't able to hangup, i am facing the same issue in you demo app also

**Comment by datso** [comment]
It would be great if you will attach tcpdump from client/server for investigation.
TCP and TLS work well for me, please re-check your configuration.

**Comment by murugancmi** [comment]
Bellow is my configuration 

let self=this;
	let configuration = {
  "name": "Murugan Pandian",
  "username": "xxxxx",
  "domain": "voip.telecmi.com",
  "password": "xxxx",
  "proxy":null,
  "transport":null,
  "regTimeout":600,
  "regServer": "voip.telecmi.com",
  "regHeaders": {
    "X-Custom-Header": "Value"
  },
  "regContactParams": ";unique-device-token-id=XXXXXXXXX",
  "regOnAdd": false,  // Default true, use false for manual REGISTRATION
};

**Comment by datso** [comment]
Try to switch transport to TCP
> "transport":"TCP"
or
> "proxy:": `sip:${a.server}:${a.sipPort};transport=tcp`

**Comment by murugancmi** [comment]
ok let me try

**Comment by murugancmi** [comment]
Still same issue  

let self=this;
let configuration = {
"name": "Murugan Pandian",
"username": "xxxxx",
"domain": "voip.telecmi.com",
"password": "xxxx",
"proxy":null,
"transport":"TCP",
"regTimeout":600,
"regServer": "voip.telecmi.com",
"regHeaders": {
"X-Custom-Header": "Value"
},
"regContactParams": ";unique-device-token-id=XXXXXXXXX",
"regOnAdd": false, // Default true, use false for manual REGISTRATION
};

**Comment by datso** [comment]
Ok, please attach logs and tcpdump for investigation. I will take a look when I'll have time.

**Comment by murugancmi** [comment]
Now i can able to register and i can able to make call ,But i can't able hangup the call when call is ringing, i can able to hangup when call answered , Is there any way i can fix this issue

**Comment by datso** [comment]
The hangup issue is caused by a code in a pjsua_call_hangup function. 
Instead of calling `hangupCall` use `declineCall` method when a call is not answered, this should solve the problem.

**Comment by murugancmi** [comment]
Same problem even use declineCall  method when a call is not answered

**Comment by datso** [comment]
Found an issue with pjsip on Android, the fix is to upgrade library to latest version.
I will make a PR soon.

**Comment by datso** [comment]
@murugancmi Please upgrade to the latest version 2.7.0. I couldn't reproduce this issue on latest Android version.

**Comment by murugancmi** [comment]
@datso i will check tomorrow

**Comment by datso** [comment]
Please re-open the ticket once you have the issue with transports on a latest version.

**Comment by kiko111pro** [comment]
TCP still not working in iOS 16.1 physical device but works fine in iOS simulator with same version and model. UDP works fine In both
