### ISSUE TITLE
TURN/STUN Server config

### ISSUE THREAD

**Issue by rcorrie** [datso/react-native-pjsip#36]
Is there any way to modify TURN/STUN server information via the JS api?

Great job with this library, btw!

**Comment by rcorrie** [comment]
Thanks!

 will give it a shot, I don't have much experience beyond the JS side of things. 

Do you have any tips or suggestions worth sharing?

**Comment by datso** [comment]
As I know STUN/TURN settings could be configured per account and globally. It would be great if we could configure the library in start & account create commands.

I could write an implementation on the next days. It would be great if you could help me with documentation and testing ?

**Comment by rcorrie** [comment]
@datso that would be great, I can help you with that.

**Comment by rcorrie** [comment]
@florindumitru this is supported now. 

You can set stun servers when starting your app, like so:
```
voipEndpoint.start({
    service: {
        stun: ['stun.l.google.com:19302','stun4.l.google.com:19302']
    }
})
```

And you can update your stun servers, like so:
```
voipEndpoint.updateStunServers(accountId, [
    'stun.l.google.com:19302',
    'stun4.l.google.com:19302'
])
```

**Comment by florindumitru** [comment]
And turn servers ?
