### ISSUE TITLE
Cannot handle incoming state in Android

### ISSUE THREAD

**Issue by imakou** [datso/react-native-pjsip#50]
Hi,

I just run the app on my emulator based on SDK 23.
The problem is triggered when I use another device to call my app.
It shows initializing, then it is terminated after a few seconds.
I figure out the message which comes from the state ``PJSIP_INV_STATE_NULL``.
I have no idea how to turn into ``PJSIP_INV_STATE_INCOMING``??

Any idea?

btw, works fine in iOS

**Comment by datso** [comment]
It is possible that codecs are incompatible, or many other cases could happen. Please attach the pjsip logs that shows the problem.

**Comment by datso** [comment]
@imakou Please provide logs, or any other information that I could use to reproduce the issue.

**Comment by omar-othmann** [comment]
in PjSipBroadcastEmiter

func: public void fireCallReceivedEvent(PjSipCall call)

there you know is incoming call

for example:
public void fireCallReceivedEvent(PjSipCall call) {
        if(haveCall){
            try {
                CallOpParam prm = new CallOpParam(true);
                prm.setStatusCode(pjsip_status_code.PJSIP_SC_BUSY_HERE);
                call.hangup(prm);
                prm.delete();
            } catch (Exception e) {
                e.printStackTrace();
            }
            return;
        }
        if(DelListener.callListener != null){
            DelListener.callListener.onCall(call);
            haveCall = true;
        }
    }
---------------------------------
you can make static class with listener
for example:
public class DelListener {
    public static CallListener callListener;
    public static CallListenerCommands callListenerCommands;
    public static interface CallListener{
        public void onCall(Call call);
    }

    public static interface CallListenerCommands{
        public void onStateChange(Call call);
        public void onCallCancel(Call call);
    }



    public static void setOnCallListener(CallListener call){
        callListener = call;
    }

    public static void setOnCallListenerCommands(CallListenerCommands call){
        callListenerCommands = call;
    }

}
--------------------------------
in your application service implements DelListener.CallListener
now you have func: onCall(Call call) in your application service

@Override
    public void onCall(Call call) {
        Intent dialogIntent = new Intent(this, IncomingCallActivity.class);
        dialogIntent.putExtra("id", call.getId());
        dialogIntent.putExtra("username", "Omar Othman");
        dialogIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        startActivity(dialogIntent);
    }

in your incomingCallActivity
getIntent()
example:
private int callId = 0;
onCreate:
Intent i = getIntent();
callId = i.getIntExtra("id", -1);

now if answer button clicked:
intent = new Intent(PjActions.ACTION_ANSWER_CALL, null, this, PjSipService.class);
intent.putExtra("call_id", callId);
startService(intent);

if decline button clicked:
intent = new Intent(PjActions.ACTION_DECLINE_CALL, null, this, PjSipService.class);
intent.putExtra("call_id", callId);
startService(intent);

that's all
you need to create layout for incomingcall and activity,  change the code to your application
is very easy!

don't  forget to set DelListener in your application service: onCreate
DelListener.setOnCallListener(this);

**Comment by datso** [comment]
@omar-othmann What actually solves your code example ?

**Comment by imakou** [comment]
Hi Vadim,
I can not run the app on my emulator now.
It seems that everything works fine but handling the incoming phone call.
It always shows " initializing".

Where can I get the logs for you?

![screenshot_1516648030](https://user-images.githubusercontent.com/1507950/35239165-b421e056-ff7d-11e7-86e7-0d12fd8a9f53.png)

**Comment by datso** [comment]
So, this is the demo application, I don't have plans to fix the bugs for this application.
