### ISSUE TITLE
Facing errors when replace newer VialerPJSIP.framework version from Vialer-pjsip-iOS

### ISSUE THREAD

**Issue by imakou** [datso/react-native-pjsip#53]
Hi,

The situation is that I got the newest ` Vialer-pjsip-iOS` and compile it to generate a newer VialerPJSIP.framework and replace old one.

But, the following errors occur when I use new VialerPJSIP.framework and build it on XCode

```
Undefined symbols for architecture arm64:
  "_pjsua_vid_dev_count", referenced from:
      -[PjSipEndpoint changeOrientation:] in libRTCPjSip.a(PjSipEndpoint.o)
  "_pjsua_vid_dev_set_setting", referenced from:
      -[PjSipEndpoint changeOrientation:] in libRTCPjSip.a(PjSipEndpoint.o)
  "_pjsua_vid_preview_get_win", referenced from:
      -[PjSipPreviewVideoViewManager set_deviceId:forView:withDefaultView:] in libRTCPjSip.a(PjSipPreviewVideoViewManager.o)
  "_pjsua_vid_preview_param_default", referenced from:
      -[PjSipPreviewVideoViewManager set_deviceId:forView:withDefaultView:] in libRTCPjSip.a(PjSipPreviewVideoViewManager.o)
  "_pjsua_vid_preview_start", referenced from:
      -[PjSipPreviewVideoViewManager set_deviceId:forView:withDefaultView:] in libRTCPjSip.a(PjSipPreviewVideoViewManager.o)
  "_pjsua_vid_win_get_info", referenced from:
      -[PjSipVideo setWindowId:] in libRTCPjSip.a(PjSipVideo.o)
      -[PjSipVideo layoutSubviews] in libRTCPjSip.a(PjSipVideo.o)
  "_pjsua_vid_win_set_size", referenced from:
      _onCallMediaEvent in libRTCPjSip.a(PjSipEndpoint.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

Please advise.

Thanks

**Comment by datso** [comment]
Hello, probably you build this library only for x86 platform

**Comment by datso** [comment]
Does it work for emulator ?, I think you faced this issue during deploying to your mobile phone ?

**Comment by imakou** [comment]
Hi,
It does not work on the emulator. The errors occur when I was deploying to my mobile devices, yes you are right.

Should I modify the compiling setting for this module? If So, which platform I should choose?

By default, it seems that Vialer-pjsip-iOS will build libraries for the following platforms.

```
AVIALABLE_ARCHS=(
    "armv7"
    "armv7s"
    "arm64"
    "i386"
    "x86_64"
)
```

Thanks for your helps!

**Comment by datso** [comment]
I think that rebuild is redundant here :)
Just grab the latest version from https://github.com/VoIPGRID/Vialer-pjsip-iOS/blob/develop/Pod/VialerPJSIP.a and update the headers directory.

**Comment by datso** [comment]
Looks like the desired IP6 feature is there.

**Comment by imakou** [comment]
Hi Vadim,

Thanks for your tips.
I can replace the newer `Vialer-pjsip-iOS` version in this module.
And it works on my devices but emulators doest not.........o_O?
In addition, my app gets `Bad Gateway` error message still.

Should I try to solve this issue by modifying client's settings?
Or, our server has to enable some settings instead?

Again, always appreciate this project and your help!

**Comment by datso** [comment]
Try to clean the build in Xcode, may be you have cached smth.
I don't know which configuration you use, and anything about your server :)

You can provide the logs from the pjsip here, but I think that they will not help because you already know that server address is not the correct one.

**Comment by imakou** [comment]
Hi Vadim,

I've deleted `build` directory and clean project then build again, but I got the same errors still.

1. Download `headers` and `VialerPJSIP.a` from [VialerPJSIP](https://github.com/VoIPGRID/Vialer-pjsip-iOS/tree/develop/Pod)
2. Replaced original *.h files and `VialerPJSIP` which are in in `node_modules/react-native-pjsip/ios/VialerPJSIP.framework/`, with newer version files just downloaded. 
3. Fix headers' references by adding `VialerPJSIP/`
  e.g. `#include <pjsip.h>` to `#include <VialerPJSIP/pjsip.h>`
  lots of files have to deal in this step.
4. <kbd>CMD</kbd> + <kbd>SHIFT</kbd> + + <kbd>K</kbd> to clean the cache
5. Built and run on my device(iPhone) is working fine, but it jumps lots of error as following

---
The errors seem relating platform..?

```
Undefined symbols for architecture x86_64:
  "_pjsip_generic_string_hdr_init2", referenced from:
      -[PjSipAccount initWithConfig:] in libRTCPjSip.a(PjSipAccount.o)
      +[PjSipUtil fillHdrList:dict:] in libRTCPjSip.a(PjSipUtil.o)
      -[PjSipCall redirect:] in libRTCPjSip.a(PjSipCall.o)
  "_pjsip_get_status_text", referenced from:
      -[PjSipAccount toJsonDictionary] in libRTCPjSip.a(PjSipAccount.o)
  "_pjsua_acc_add", referenced from:
      -[PjSipAccount initWithConfig:] in libRTCPjSip.a(PjSipAccount.o)
  "_pjsua_acc_config_default", referenced from:
      -[PjSipAccount initWithConfig:] in libRTCPjSip.a(PjSipAccount.o)
  "_pjsua_acc_del", referenced from:
      -[PjSipAccount dealloc] in libRTCPjSip.a(PjSipAccount.o)
  "_pjsua_acc_get_info", referenced from:
      -[PjSipAccount toJsonDictionary] in libRTCPjSip.a(PjSipAccount.o)
  "_pjsua_acc_set_registration", referenced from:
      -[PjSipAccount dealloc] in libRTCPjSip.a(PjSipAccount.o)
      -[PjSipAccount register:] in libRTCPjSip.a(PjSipAccount.o)
  "_pjsua_call_answer2", referenced from:
      -[PjSipCall answer] in libRTCPjSip.a(PjSipCall.o)
      -[PjSipCall redirect:] in libRTCPjSip.a(PjSipCall.o)
  "_pjsua_call_dial_dtmf", referenced from:
      -[PjSipCall dtmf:] in libRTCPjSip.a(PjSipCall.o)
  "_pjsua_call_get_info", referenced from:
      _onCallStateChanged in libRTCPjSip.a(PjSipEndpoint.o)
      _onCallMediaStateChanged in libRTCPjSip.a(PjSipEndpoint.o)
      _onCallMediaEvent in libRTCPjSip.a(PjSipEndpoint.o)
      -[PjSipCall mute] in libRTCPjSip.a(PjSipCall.o)
      -[PjSipCall unmute] in libRTCPjSip.a(PjSipCall.o)
      -[PjSipCall toJsonDictionary:] in libRTCPjSip.a(PjSipCall.o)
  "_pjsua_call_hangup", referenced from:
      -[PjSipCall hangup] in libRTCPjSip.a(PjSipCall.o)
      -[PjSipCall decline] in libRTCPjSip.a(PjSipCall.o)
  "_pjsua_call_make_call", referenced from:
      -[PjSipEndpoint makeCall:destination:callSettings:msgData:] in libRTCPjSip.a(PjSipEndpoint.o)
  "_pjsua_call_reinvite", referenced from:
      -[PjSipCall unhold] in libRTCPjSip.a(PjSipCall.o)
  "_pjsua_call_set_hold", referenced from:
      -[PjSipCall hold] in libRTCPjSip.a(PjSipCall.o)
  "_pjsua_call_setting_default", referenced from:
      +[PjSipUtil fillCallSettings:dict:] in libRTCPjSip.a(PjSipUtil.o)
      -[PjSipCall answer] in libRTCPjSip.a(PjSipCall.o)
      -[PjSipCall redirect:] in libRTCPjSip.a(PjSipCall.o)
  "_pjsua_call_xfer", referenced from:
      -[PjSipCall xfer:] in libRTCPjSip.a(PjSipCall.o)
  "_pjsua_call_xfer_replaces", referenced from:
      -[PjSipCall xferReplaces:] in libRTCPjSip.a(PjSipCall.o)
  "_pjsua_conf_adjust_rx_level", referenced from:
      -[PjSipCall mute] in libRTCPjSip.a(PjSipCall.o)
      -[PjSipCall unmute] in libRTCPjSip.a(PjSipCall.o)
  "_pjsua_conf_connect", referenced from:
      -[PjSipCall onMediaStateChanged:] in libRTCPjSip.a(PjSipCall.o)
  "_pjsua_config_default", referenced from:
      -[PjSipEndpoint init] in libRTCPjSip.a(PjSipEndpoint.o)
  "_pjsua_create", referenced from:
      -[PjSipEndpoint init] in libRTCPjSip.a(PjSipEndpoint.o)
  "_pjsua_init", referenced from:
      -[PjSipEndpoint init] in libRTCPjSip.a(PjSipEndpoint.o)
  "_pjsua_logging_config_default", referenced from:
      -[PjSipEndpoint init] in libRTCPjSip.a(PjSipEndpoint.o)
  "_pjsua_media_config_default", referenced from:
      -[PjSipEndpoint init] in libRTCPjSip.a(PjSipEndpoint.o)
  "_pjsua_msg_data_init", referenced from:
      +[PjSipUtil fillMsgData:dict:] in libRTCPjSip.a(PjSipUtil.o)
      -[PjSipCall answer] in libRTCPjSip.a(PjSipCall.o)
      -[PjSipCall redirect:] in libRTCPjSip.a(PjSipCall.o)
  "_pjsua_set_no_snd_dev", referenced from:
      -[PjSipModule activateAudioSession:] in libRTCPjSip.a(PjSipModule.o)
      -[PjSipModule deactivateAudioSession:] in libRTCPjSip.a(PjSipModule.o)
  "_pjsua_set_snd_dev", referenced from:
      -[PjSipModule activateAudioSession:] in libRTCPjSip.a(PjSipModule.o)
  "_pjsua_start", referenced from:
      -[PjSipEndpoint init] in libRTCPjSip.a(PjSipEndpoint.o)
  "_pjsua_transport_config_default", referenced from:
      -[PjSipEndpoint init] in libRTCPjSip.a(PjSipEndpoint.o)
  "_pjsua_transport_create", referenced from:
      -[PjSipEndpoint init] in libRTCPjSip.a(PjSipEndpoint.o)
  "_pjsua_vid_dev_count", referenced from:
      -[PjSipEndpoint changeOrientation:] in libRTCPjSip.a(PjSipEndpoint.o)
  "_pjsua_vid_dev_set_setting", referenced from:
      -[PjSipEndpoint changeOrientation:] in libRTCPjSip.a(PjSipEndpoint.o)
  "_pjsua_vid_preview_get_win", referenced from:
      -[PjSipPreviewVideoViewManager set_deviceId:forView:withDefaultView:] in libRTCPjSip.a(PjSipPreviewVideoViewManager.o)
  "_pjsua_vid_preview_param_default", referenced from:
      -[PjSipPreviewVideoViewManager set_deviceId:forView:withDefaultView:] in libRTCPjSip.a(PjSipPreviewVideoViewManager.o)
  "_pjsua_vid_preview_start", referenced from:
      -[PjSipPreviewVideoViewManager set_deviceId:forView:withDefaultView:] in libRTCPjSip.a(PjSipPreviewVideoViewManager.o)
  "_pjsua_vid_win_get_info", referenced from:
      -[PjSipVideo setWindowId:] in libRTCPjSip.a(PjSipVideo.o)
      -[PjSipVideo layoutSubviews] in libRTCPjSip.a(PjSipVideo.o)
  "_pjsua_vid_win_set_size", referenced from:
      _onCallMediaEvent in libRTCPjSip.a(PjSipEndpoint.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by datso** [comment]
I will try to update the library for iOS but it always the pain to work with native code :)

**Comment by datso** [comment]
@imakou Faced the same issue with linker, when trying to run it on emulator, but for production build it works well, I just copy the new .framework and everything works.

> cd ./ios && xcodebuild -scheme "ProjectName" -configuration Release archive -archivePath ./ProjectName.xcarchive

To fix the issue with xcode, try to close the xcode and then remove following folders
> ~/Library/Developer/Xcode/DerivedData/RTCPjSip-****
> ~/Library/Developer/Xcode/DerivedData/ProjectName-****

\* xcode is very buggy it terms of the cache, closing and opening xcode again usually solves the problem :)

\* VialerPJSIP has the correct archs
> lipo -info ios/VialerPJSIP.framework/VialerPJSIP
> Architectures in the fat file: ios/VialerPJSIP.framework/VialerPJSIP are: i386 armv7 armv7s arm64 x86_64

**Comment by imakou** [comment]
Hi Vadim,

😂 
It's a huge challenge for me to understand c, obj-c these native code...
However, my major purpose is to implement [NAT64](https://trac.pjsip.org/repos/wiki/IPv6).
Therefore, I need IP6 features base on the newest VialerPJSIP.

But I was facing similar errors when I built `VialerPJSIP.framework` by running `./vialerbuild`.

![screen shot 2018-01-15 at 2 53 56 pm](https://user-images.githubusercontent.com/1507950/34959690-99d8142c-fa05-11e7-9c8e-2a505eb7f5e4.png)

Even though I try your advice to clean cache's folders.
The tricky thing is that it works when I use the `VialerPJSIP.framework` built from [repo](https://github.com/VoIPGRID/Vialer-pjsip-iOS/blob/develop/Pod/VialerPJSIP.a)

In your case, you just replace the new `.framework` only and it works well with old headers?

**Comment by datso** [comment]
I've changed also the headers - it doesn't work for build in xcode, but for production build it does.
I will handle this, currently rebuilding the library from the sources...

**Comment by datso** [comment]
I've got some errors during build 264 codec from latest sources... Do not have more time to spend on that.

The strange this is that 3.2.0 version works well. Just to copy VialerPJSIP.a and everything that inside the Pod/vialer-pjsip-include/* to headers.

**Comment by imakou** [comment]
Hi Vadim,

Thanks for your hard work❤️.
I have compiled 3.3.0 for many times today.
But I just got same type errors always 😂.

I found a tiny bug for enabling IPV6 and push a [PR](https://github.com/VoIPGRID/Vialer-pjsip-iOS/pull/23) for 3.3.0.

However, the problem is still existing...
Still, I am struggled with hooking VialerPJSIP and RN PJSIP(this repo) lol

**Comment by imakou** [comment]
Hi Vadim,

It seems that VialerPjsip 3.2.0 causes a new issue as `Service Unavailable`.
The situation is when users try to register to sip server. 
In this case, I just replaced old version by new `.framework` and `headers in ver 3.2.0. 😂
The registered status as following obj in the console.

```javascript
AccountRegistration{
  "_status": "Service Unavailable",
  "_statusText": "Service Unavailable",
  "_active": "test",
  "_reason": "test"
}
```

**Comment by datso** [comment]
May be this is the response from the server ? Does the library send anything to server ?

**Comment by imakou** [comment]
Hi Vadim,

It is not an issue, it just because I modified `PjSipEndpoint.m` by following[this tutorial](https://trac.pjsip.org/repos/wiki/IPv6#CreatingSIPtransport).
It works when I just reset the file. Sorry about.🙇

**Comment by imakou** [comment]
Hi Vadim,

The errors are related video feature. 
In order to pass the compile processIs, is there any way to turn off the video function in files in `RTCPjSip` folder?

Thank you so much.

![screen shot 2018-01-15 at 2 53 56 pm](https://user-images.githubusercontent.com/1507950/34959690-99d8142c-fa05-11e7-9c8e-2a505eb7f5e4.png)

**Comment by datso** [comment]
Just comment files and includes that requires *.h file (video one), so you build the library without the video capability ?

**Comment by imakou** [comment]
Hi Vadim,

The following is our situations

- Success 
  -  We copy `binary file(.framework)` from 3.2.0 and 3.3.0 in [Github](https://github.com/VoIPGRID/Vialer-pjsip-iOS/blob/develop/Pod/VialerPJSIP.a)
  - We also replace `headers` folder.

- Failure 
  - We built `.framework` by myself and replace the current one. 
  - We don't know if we should add options before executing `./vialerbuild`? Any suggestion?
  - The errors messages show in the above picture.

So, we'd like disable video's capabilities since the errors are relevant video.
But I will try to put some options in my building command for a new binary file.
Would you let me know what options you put when you build binary file?

It's always happy to see your replying. 😄

**Comment by datso** [comment]
vialerbuild builds pjsip with video, you copy files from which directory ? Pod ?

**Comment by imakou** [comment]
Vadim,

YEs, from Pod.

**Comment by datso** [comment]
I would suggest just to comment & remove files that related to video, it would take less time then to check why video headers could not be linked.

**Comment by datso** [comment]
@imakou Could I close this ticket ? how is your adventure on ipv6 btw ? :)

**Comment by imakou** [comment]
Hi Vadim,

Still, struggle with IPV6 😂.
I am very appreciating your help!

**Comment by datso** [comment]
Did you tried the following:
1) Add transports creation to react-native-pjsip/android/src/main/java/com/carusto/ReactNativePjSip/PjSipService.java
```


            // Configure transports (IPv6)
            {
                TransportConfig transportConfig = new TransportConfig();
                transportConfig.setQosType(pj_qos_type.PJ_QOS_TYPE_VOICE);
                mUdpTransportId = mEndpoint.transportCreate(pjsip_transport_type_e.PJSIP_TRANSPORT_UDP6, transportConfig);
                mTrash.add(transportConfig);
            }
            {
                TransportConfig transportConfig = new TransportConfig();
                transportConfig.setQosType(pj_qos_type.PJ_QOS_TYPE_VOICE);
                mTcpTransportId = mEndpoint.transportCreate(pjsip_transport_type_e.PJSIP_TRANSPORT_TCP6, transportConfig);
                mTrash.add(transportConfig);
            }
            {
                TransportConfig transportConfig = new TransportConfig();
                transportConfig.setQosType(pj_qos_type.PJ_QOS_TYPE_VOICE);
                mTlsTransportId = mEndpoint.transportCreate(pjsip_transport_type_e.PJSIP_TRANSPORT_TLS6, transportConfig);
                mTrash.add(transportConfig);
            }
```

2) Rebuild the library https://github.com/datso/react-native-pjsip-builder with IPv6 flags (run ./build_android)
```
#define PJMEDIA_HAS_G7221_CODEC 1
#include <pj/config_site_sample.h>
+ #define PJ_HAS_IPV6 1
#define PJMEDIA_HAS_VIDEO 1
```

3) Copy .so files from android-dist to pjsip/android/src/main/jniLibs (respect the arch folders)
4) react-native run-android

**Comment by imakou** [comment]
Hi Vadim,

I haven't started to fix Android ver.
I am still trying to fix for iOs.
I upgrade the latest you just update ver from `datso/react-native-pjsip` and I facing an error:

> error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /my_project/node_modules/react-native-pjsip/ios/VialerPJSIP.framework/VialerPJSIP is not an object file (not allowed in a library)

**Comment by datso** [comment]
To save the time I suggest you to start from Android :) It is easier because it doesn't require to copy headers and linking is done in Docker.

**Comment by imakou** [comment]
Hi Vadim,

Took a while to build Android Libs.
The result is not a good news.
The app can not even be opened by changing the settings you suggested.
On the other hand, our real Android device can not connect to internet by an ipv6 wifi environment o_O...

**Comment by bryanfarris** [comment]
Having the same issue on iOS still.

Reverting back to the old `VialerPJSIP.framework` worked for me. 

To fix:
1. Point your `package.json` to an older commit of `react-native-pjsip`
2. Run `npm install`
2. Navigate to `node_modules/react-native-pjsip/ios/`
3. Copy the `VialerPJSIP.framework` to somewhere else
4. Point your `package.json` to an older commit of `react-native-pjsip`
5. Run `npm install`
6. Navigate to `node_modules/react-native-pjsip/ios/`
7. Replace the `VialerPJSIP.framework` with the one you copied in step 3
8. Clean Build Folder
9. Run!

**Comment by datso** [comment]
@imakou Please reopen the issue if you still have a problem, I've made an update on https://github.com/datso/react-native-pjsip-builder that copy the libs from Vialer.
