### ISSUE TITLE
Error while starting PJSIP

### ISSUE THREAD

**Issue by omar-othmann** [datso/react-native-pjsip#55]
E/PjSipService: Error while starting PJSIP
                java.lang.Exception: Title:       pjsua_transport_create(type, &tcfg, &tid)
                Code:        171060
                Description: Unsupported transport (PJSIP_EUNSUPTRANSPORT)
                Location:    ../src/pjsua2/endpoint.cpp:1526

                    at org.pjsip.pjsua2.pjsua2JNI.Endpoint_transportCreate(Native Method)
                    at org.pjsip.pjsua2.Endpoint.transportCreate(Endpoint.java:178)
                    at com.carusto.ReactNativePjSip.PjSipService.load(PjSipService.java:197)
                    at com.carusto.ReactNativePjSip.PjSipService.access$100(PjSipService.java:52)
                    at com.carusto.ReactNativePjSip.PjSipService$2.run(PjSipService.java:236)
                    at android.os.Handler.handleCallback(Handler.java:751)
                    at android.os.Handler.dispatchMessage(Handler.java:95)
                    at android.os.Looper.loop(Looper.java:154)
                    at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by datso** [comment]
Why u rebuild the library ? Did you add some more flags into the configuration ?

**Comment by omar-othmann** [comment]
i have add in  openssl configuration: -no-asm

**Comment by datso** [comment]
yes, latest version doesnt have text relocations.

**Comment by omar-othmann** [comment]
Ok Thank you for help!

i try it.

**Comment by omar-othmann** [comment]
i can fix this problem for libopen264.so but libpjsua2.so i can't

**Comment by datso** [comment]
You can copy it from Docker conatiner, just paste at the end of Docker file
RUN find / -name 'libpjsua2.a'

and then copy the binary to the host machine using docker cp.

**Comment by omar-othmann** [comment]
I have a question
Have you tested on Android 6 x86?

**Comment by omar-othmann** [comment]
i thing you have error when you build native library have you change libopenh264.a to libopenh264.so
without android ndk-build?

**Comment by omar-othmann** [comment]
Do you have .a files for this library? I will convert it via android studio
i have RUN find / -name  'libpjsua2.a' i got no result

**Comment by omar-othmann** [comment]
But I have converted the libopenh264.a file from Windows and not from Linux

Ndk in windows:
C:\Users\Omar>ndk-build -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i586-pc-mingw32

C:\Users\Omar>

**Comment by datso** [comment]
you can find the .a files inside the Docker container that builds the library - https://github.com/datso/react-native-pjsip-builder

**Comment by datso** [comment]
@omar-othmann Let me know whether the problem is still reproduced on latest version (2.7.3)
