### ISSUE TITLE
Calls cannot be muted/unmuted on iOS

### ISSUE THREAD

**Issue by bryanfarris** [datso/react-native-pjsip#56]
Hi all - we are facing an issue on iOS where the microphone is not muted when the user presses mute.

In our code we are doing:

`const { activeCallId, calls, endpoint } = this.state`
`endpoint.muteCall(calls[activeCallId])`

And I can trace this through logs to see that the appropriate code is running on PJSIP but unfortunately the microphone is not muted & the other parties on the call can still hear the person who was muted.

In case it is relevant, other functions such as hold/unhold and useSpeaker/useEarpiece do function properly and we call them in a very similar manner.

Anyone else facing this issue?

**Comment by datso** [comment]
Yeap, known issue, going to fix this soon.

**Comment by rcorrie** [comment]
I am working on a PR for this. 

Looking through the code, It seems like it isn't a bug, but actually it is a misunderstanding of the feature. 

The incoming audio is being muted, instead of the mic.

right @datso ?

**Comment by datso** [comment]
Yeap, its a bug

**Comment by datso** [comment]
So instead of adjustRxLevel a level of audio, it should call stopTransmit, see onCallMediaState for android

**Comment by rcorrie** [comment]
Going to submit PR in a few moments. iOS is good to go, just testing Android code now @datso
