### ISSUE TITLE
pjsip app demo not working

### ISSUE THREAD

**Issue by viet97** [datso/react-native-pjsip#58]
i  have clone react-native-pjsip-app and run.after i filled all required fields then i click OK but nothing happened. why is that ? anybody  has the same problem?

**Comment by datso** [comment]
@viet97 currently react-native-pjsip-app is outdated and requires an update for the latest version of RN and pjsip library.

**Comment by datso** [comment]
I mean that you can use that example to build your own application.

**Comment by lavarajallu** [comment]
How can i integrate on iOS in react-native
