### ISSUE TITLE
All the jniLibs libopenh264.so and libpjsua2.so files are 132 bytes  -- lfs ???

### ISSUE THREAD

**Issue by saket424** [datso/react-native-pjsip#63]
ls -l `find . -name *.so`
-rwxrwxr-x 1 anand anand 132 Jan 28 18:13 ./react-native-pjsip/android/src/main/jniLibs/arm64-v8a/libopenh264.so
-rwxrwxr-x 1 anand anand 132 Jan 28 18:13 ./react-native-pjsip/android/src/main/jniLibs/arm64-v8a/libpjsua2.so
-rwxrwxr-x 1 anand anand 132 Jan 28 18:13 ./react-native-pjsip/android/src/main/jniLibs/armeabi-v7a/libopenh264.so
-rwxrwxr-x 1 anand anand 132 Jan 28 18:13 ./react-native-pjsip/android/src/main/jniLibs/armeabi-v7a/libpjsua2.so
-rwxrwxr-x 1 anand anand 132 Jan 28 18:13 ./react-native-pjsip/android/src/main/jniLibs/x86_64/libopenh264.so
-rwxrwxr-x 1 anand anand 132 Jan 28 18:13 ./react-native-pjsip/android/src/main/jniLibs/x86_64/libpjsua2.so
-rwxrwxr-x 1 anand anand 132 Jan 28 18:13 ./react-native-pjsip/android/src/main/jniLibs/x86/libopenh264.so
-rwxrwxr-x 1 anand anand 132 Jan 28 18:13 ./react-native-pjsip/android/src/main/jniLibs/x86/libpjsua2.so

anand@Alien15:/tmp$ cat ./react-native-pjsip/android/src/main/jniLibs/arm64-v8a/libopenh264.so
version https://git-lfs.github.com/spec/v1
oid sha256:a1b4b356c38fe67f294d63c29c18f24d5a5c8c237191873d8a4960a95e23db93
size 1112328

**Comment by saket424** [comment]
I guess the above are 8 out of the 9 files in LFS purgatory. Which one is the 9th one?

nand@Alien15:/tmp/react-native-pjsip$ git-lfs pull
Git LFS: (0 of 9 files) 0 B / 168.78 MB                                        
batch response: This repository is over its data quota. Purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/datso/react-native-pjsip.git/info/lfs'

**Comment by saket424** [comment]
The 9th one is  react-native-pjsip/ios/VialerPJSIP.framework/VialerPJSIP

**Comment by datso** [comment]
The reason of error is the LFS quota that exceeds just in one day, didn't expect that. I will remove binaries from the repo and add them only in release section.

Currently you can find binaries only in NPM repo.

**Comment by saket424** [comment]
when i do a npm install react-native-pjsip , I get the lfs links to the large files there as well
How do I get the 9 large binaries? Please put them in the release section. Thanks

**Comment by datso** [comment]
ls -lah ./node_modules/react-native-pjsip//android/src/main/jniLibs/**/*.so

```
-rwxr-xr-x  1 vruban  staff   1.1M Jan 19 17:59 ./node_modules/react-native-pjsip//android/src/main/jniLibs/arm64-v8a/libopenh264.so
-rwxr-xr-x  1 vruban  staff   9.4M Jan 19 17:59 ./node_modules/react-native-pjsip//android/src/main/jniLibs/arm64-v8a/libpjsua2.so
-rwxr-xr-x  1 vruban  staff   1.0M Jan 19 18:14 ./node_modules/react-native-pjsip//android/src/main/jniLibs/armeabi-v7a/libopenh264.so
-rwxr-xr-x  1 vruban  staff   4.4M Jan 19 18:14 ./node_modules/react-native-pjsip//android/src/main/jniLibs/armeabi-v7a/libpjsua2.so
-rwxr-xr-x  1 vruban  staff   1.4M Jan 19 18:14 ./node_modules/react-native-pjsip//android/src/main/jniLibs/x86/libopenh264.so
-rwxr-xr-x  1 vruban  staff   9.0M Jan 19 18:14 ./node_modules/react-native-pjsip//android/src/main/jniLibs/x86/libpjsua2.so
-rwxr-xr-x  1 vruban  staff   1.3M Jan 19 17:59 ./node_modules/react-native-pjsip//android/src/main/jniLibs/x86_64/libopenh264.so
-rwxr-xr-x  1 vruban  staff   9.5M Jan 19 17:59 ./node_modules/react-native-pjsip//android/src/main/jniLibs/x86_64/libpjsua2.so
```

**Comment by saket424** [comment]
Try checking out from today. Your's has a time stamp from Jan 19

ls -lah ./node_modules/react-native-pjsip//android/src/main/jniLibs/**/*.so
-rwxrwxr-x 1 anand anand 132 Jan 28 13:08 ./node_modules/react-native-pjsip//android/src/main/jniLibs/arm64-v8a/libopenh264.so
-rwxrwxr-x 1 anand anand 132 Jan 28 13:08 ./node_modules/react-native-pjsip//android/src/main/jniLibs/arm64-v8a/libpjsua2.so
-rwxrwxr-x 1 anand anand 132 Jan 28 13:08 ./node_modules/react-native-pjsip//android/src/main/jniLibs/armeabi-v7a/libopenh264.so
-rwxrwxr-x 1 anand anand 132 Jan 28 13:08 ./node_modules/react-native-pjsip//android/src/main/jniLibs/armeabi-v7a/libpjsua2.so
-rwxrwxr-x 1 anand anand 132 Jan 28 13:08 ./node_modules/react-native-pjsip//android/src/main/jniLibs/x86_64/libopenh264.so
-rwxrwxr-x 1 anand anand 132 Jan 28 13:08 ./node_modules/react-native-pjsip//android/src/main/jniLibs/x86_64/libpjsua2.so
-rwxrwxr-x 1 anand anand 132 Jan 28 13:08 ./node_modules/react-native-pjsip//android/src/main/jniLibs/x86/libopenh264.so
-rwxrwxr-x 1 anand anand 132 Jan 28 13:08 ./node_modules/react-native-pjsip//android/src/main/jniLibs/x86/libpjsua2.so

**Comment by datso** [comment]
Which version do you use ? If it is a git link for sure you will have this issue. 

package.json
```
"react-native-pjsip": "2.7.1",
```

**Comment by saket424** [comment]
I did an "npm install react-native-pjsip" by explicitly specifying "2.7.1" and not the git link in the package.json and I still have the issue

**Comment by datso** [comment]
I cant reproduce that, even in Docker :)

Dockerfile
```
FROM electronuserland/builder:wine

RUN mkdir /tmp/test && \
    cd /tmp/test && \
    yarn init --yes &&  \
    yarn add react-native-pjsip

RUN ls -lah /tmp/test/node_modules/react-native-pjsip//android/src/main/jniLibs/**/*.so
```

Output (docker build .)
```
Step 1/3 : FROM electronuserland/builder:wine
 ---> 34773f763ba1
Step 2/3 : RUN mkdir /tmp/test &&     cd /tmp/test &&     yarn init --yes &&      yarn add react-native-pjsip
 ---> Running in 0fc5e867428b
yarn init v1.3.2
warning The yes flag has been set. This will automatically answer yes to all questions which may have security implications.
success Saved package.json
Done in 0.04s.
yarn add v1.3.2
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > react-native-pjsip@2.7.1" has unmet peer dependency "react-native@>=0.40.0".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 2 new dependencies.
├─ events@1.1.0
└─ react-native-pjsip@2.7.1
Done in 13.00s.
Removing intermediate container 0fc5e867428b
 ---> cbac75d23f75
Step 3/3 : RUN ls -lah /tmp/test/node_modules/react-native-pjsip//android/src/main/jniLibs/**/*.so
 ---> Running in ade3a265997d
-rwxr-xr-x 1 root root  1.1M Jan 29 15:24 /tmp/test/node_modules/react-native-pjsip//android/src/main/jniLibs/arm64-v8a/libopenh264.so
-rwxr-xr-x 1 root root  9.4M Jan 29 15:24 /tmp/test/node_modules/react-native-pjsip//android/src/main/jniLibs/arm64-v8a/libpjsua2.so
-rwxr-xr-x 1 root root 1016K Jan 29 15:24 /tmp/test/node_modules/react-native-pjsip//android/src/main/jniLibs/armeabi-v7a/libopenh264.so
-rwxr-xr-x 1 root root  4.4M Jan 29 15:24 /tmp/test/node_modules/react-native-pjsip//android/src/main/jniLibs/armeabi-v7a/libpjsua2.so
-rwxr-xr-x 1 root root  1.4M Jan 29 15:24 /tmp/test/node_modules/react-native-pjsip//android/src/main/jniLibs/x86/libopenh264.so
-rwxr-xr-x 1 root root  9.0M Jan 29 15:24 /tmp/test/node_modules/react-native-pjsip//android/src/main/jniLibs/x86/libpjsua2.so
-rwxr-xr-x 1 root root  1.4M Jan 29 15:24 /tmp/test/node_modules/react-native-pjsip//android/src/main/jniLibs/x86_64/libopenh264.so
-rwxr-xr-x 1 root root  9.5M Jan 29 15:24 /tmp/test/node_modules/react-native-pjsip//android/src/main/jniLibs/x86_64/libpjsua2.so
Removing intermediate container ade3a265997d
 ---> 714be25478f8
Successfully built 714be25478f8
```

**Comment by saket424** [comment]
Hmm. when I used yarn it worked aand I get all the 9 fat binaries. Thanks for looking into this issue
