### ISSUE TITLE
video-support confusion

### ISSUE THREAD

**Issue by saket424** [datso/react-native-pjsip#64]
@datso ,
Question. I am unclear exactly how to enable 2 way-video (preview + remote video) using a combination of react-native-pjsip and react-native-pjsip-app. For starters the video call button is not plumbed in. When I make an incoming video call from a different client, the remote client gets the iOS video but the react-native-pjsip-app ios client does not render any video

I notice there is a xcodeproject in react-native-pjsip itself but it fails to compile due to RCTUtil.h not being found. Is react-native-pjsip a self contained project or does it need react-native-pjsip-app also ? I am assuming the two go together 

How do I get the video button to function ( audio call button functions) ? And secondly, where is the rendering of the video on the iOS client hidden? I am unable to understand if I am missing a step or what

Thanks in advance

**Comment by datso** [comment]
react-native-pjsip-app doesn't have a video screen yet, I didn't update this app for a long time.

Here is the example how to use video:
```
...
import PreviewVideoView from 'react-native-pjsip/src/PreviewVideoView'
import RemoteVideoView from 'react-native-pjsip/src/RemoteVideoView'
....
  render() {
    const videoMedia = call.getMedia().find((media) => media['type'] === 'PJMEDIA_TYPE_VIDEO')

    return (
        <View style={s.container}>
          <RemoteVideoView
            style={{position: 'absolute', top: 0, bottom: 0, left: 0, right: 0, backgroundColor: "#333"}}
            windowId={media.videoStream.windowId}
            objectFit="contain"
          />
          <PreviewVideoView
            style={{position: 'absolute', bottom: 10, right: 10, width: 96, height: 96, backgroundColor: "#000"}}
            deviceId={media.videoStream.captureDevice}
            objectFit="contain"
          />
        </View>
    )
  }
}
```

**Comment by saket424** [comment]
@datso,
Can you please be a bit more specific on which file these render changes go into and possibly include a patch file with the suggested changes if that is not too much to ask.
I tried a crude attempt at adding it to react-native-pjsip-app/app/screens/CallScreen/index.js and did not get very far since all this is new to me.

Thanks again

**Comment by saket424** [comment]
[index.js.patch.txt](https://github.com/datso/react-native-pjsip/files/1681861/index.js.patch.txt)
Here is a crude patch that works.
Apply to react-native-pjsip-app/app/screens/CallScreen/index.js

**Comment by ppthakur** [comment]
Hello,
I am able to achieve audio / video communication by adding the components on call screen ass mentioned by you. Thanks for that.
Now the problem I am facing is "PreviewVideoView" is hiding most of the time from mobile.
It work fine for the very fist time but when we initiate call again it will just show you the "RemoteVideoView"
of other person but not "PreviewVideoView".But yes both the ends are able to see themselves and only small thumbnail video is missing at bottom right.
 
Please share why is this happening and how can we fix it? 

Regards,
Prithipal

**Comment by varunprashar5** [comment]
> Hello,
> I am able to achieve audio/video communication by adding the components to the call screen as mentioned by you. Thanks for that.
> Now the problem I am facing is "PreviewVideoView" is hiding most of the time from mobile.
> It works fine for the very first time but when we initiate call again it will just show you the "RemoteVideoView"
> of other person but not "PreviewVideoView".But yes both the ends are able to see themselves and only small thumbnail video is missing at bottom right.
> 
> Please share why is this happening and how can we fix it?
> 
> Regards,
> Prithipal

I am also facing the same issue. Has anyone get its solution ?

**Comment by nvojnovic** [comment]
I managed to make it work with this changes b0a6411af561d21bd7e2026c4d16bf2646afcaa9
