### ISSUE TITLE
Calling Start Method on Endpoint returns "Undefined is not an object "

### ISSUE THREAD

**Issue by herlarb** [datso/react-native-pjsip#65]
@datso  am trying to follow the instructions provided  to use the PJSIP library but anytime i invoke the .start() method  on the endpoint instance i get an error " undefined is not an object (evaluating '_reactNative.NativeModules.PjSipModule.start')"

Here is my source code  
```

import React , {Component} from 'react';
import {View, Text, Platform} from 'react-native'
import {Endpoint } from 'react-native-pjsip'
import {extendObservable} from 'mobx';
import {observer} from 'mobx-react'

class EndpointStart  extends Component{
    constructor(props){
        super(props);
        extendObservable(this,{
            endpoint : new Endpoint(),
            state:{}
        }
        );
    }

    componentWillMount(){
        this._onStart();
    }

    _onStart = async()=>{
        try{
            console.warn(this.endpoint);
        this.state = await this.endpoint.start();
    }catch(err){
        console.warn('',err.message);
    }
    }

    render(){
        const {endpoint} = this;
        return <Text>Test </Text>
    }
};

export default (observer(EndpointStart));
```

**Comment by datso** [comment]
Hi, what "react-native link" shows?

**Comment by herlarb** [comment]
I had not previously linked my  the library ( my bad ) but upon linking all i get now is an empty object on state after calling .start() on endpoint instance  . I am  not conversant with redux  only mobx  but the sample app uses a lot of dispatch and redux . How can i  get the access state information such as  Calls , Accounts , Connectivity. I am quite new to the library. Kindly help

**Comment by datso** [comment]
Create a new account and then refresh the view on Android, this.state in your case shouldn't be empty.

**Comment by herlarb** [comment]
I tried creating an account with a free SIP service and all i get is undefined . The  demo credentials ( the pbx.carusto.com ) actually register but changing the credentials causes undefined to be shown

**Comment by DastoBuniq** [comment]
Hi!, I'm using ios and after the appropriate setup procedure it comes up that NativeModules.PjSipModule (row72) in Endpoint.js is undefined. Help!!
