### ISSUE TITLE
Hangup method hanging up all calls

### ISSUE THREAD

**Issue by iBuntaah** [datso/react-native-pjsip#70]
Hi, I have a problem with the hangup method when I have more than one calls simultaneously.
I mean if I call an user A, then an user B call me, I put the user A in an hold status:
- If the user B hangup its ok I can switch and unhold the user A. 
- But if I hangup myself, I receive 2 events in the terminate call listener and it terminate the 2 calls

Here is a simple piece of my code :

```javascript
static async hangupCall() {
    if(PjSip.currentCall ){
         console.log("HangupCall Myself : " + PjSip.currentCall.getId());
         console.log("In hold call : " + PjSip.callArrayOnHold[0].getId()); // my only hold call for this example
         await PjSip.endpoint.hangupCall(PjSip.currentCall);
    }
}
```
According to my logs, I pass only one time in the hangupCall method so its fine.

```javascript
PjSip.endpoint.on('call_terminated', (call) => {
      console.log('-------------------------- terminated call: ' + call.getId());
});
```
But this listener fire up two times.

Here is my logs:
02-08 16:26:48.737 15663 16007 I ReactNativeJS: HangupCall Myself : 3
02-08 16:26:48.737 15663 16007 I ReactNativeJS: In hold call : 2
02-08 16:26:48.802 15663 16007 I ReactNativeJS: -------------------------- call    terminated call: 2
02-08 16:26:48.959 15663 16007 I ReactNativeJS: -------------------------- call    terminated call: 3

I don't understand why it hanging up all my calls at the same time ?

**Comment by datso** [comment]
Hi, could you please provide the logs from adb / ios console (github gist) ?
So you describe a case when library hangs up two calls instead of one ?

**Comment by iBuntaah** [comment]
I don't really know if its the lib or my code but I simplify my code a lot and I still have this issue.

Thanks for your help.

https://gist.githubusercontent.com/iBuntaah/232be06882c26fd0945230c7d8656d3f/raw/1cbabbc17d8e4ffc55e96a94542fdb9ce958650a/gistfile1.txt

**Comment by iBuntaah** [comment]
@datso I noticed that its on the handleCallHangup method in PjSipService.java.
I uncommented the 2 lines below
//PjSipCall call = findCall(callId); 
//call.hangup(new CallOpParam(true));

And deleted mEndpoint.hangupAllCalls();  and now it works.

Hope it helps.

**Comment by datso** [comment]
@iBuntaah Thanks for the investigation, looks like I accidentally commit changes made for the tests.
