### ISSUE TITLE
Background mode (Android)

### ISSUE THREAD

**Issue by Zuken** [datso/react-native-pjsip#72]
As documentation says - background mode is handled by notification that keeps application in foreground. It's configured by `service.notifications` value when endpoint starting. I've updated my app to 2.7.3 version and there is no notification and SIP in background mode doesn't work. I'am not a Java programmer, but I didn't found any code that handles "notifications" key when endpoint starts `endpoint.start(config);`.
Is there some other way we can handle SIP in Android's background mode?

**Comment by datso** [comment]
I think that push notifications works better then startForeground / having a socket permanently connected to server. It is also not possible to have such functionality on iOS, so starting from 2.x I've removed background mode.

Please consider usage of GCM / APN for your application. Here is some info how it could work: https://github.com/datso/react-native-pjsip/blob/master/docs/ios_push_notifications_callkit.md

**Comment by DrSchmurge** [comment]
> I think that push notifications works better then startForeground / having a socket permanently connected to server. It is also not possible to have such functionality on iOS, so starting from 2.x I've removed background mode.
> 
> Please consider usage of GCM / APN for your application. Here is some info how it could work: https://github.com/datso/react-native-pjsip/blob/master/docs/ios_push_notifications_callkit.md

Hi datso,
On Android 9+, after going to background mode, when being in active call,  the stream from microphone is being cut after 1minute of talking. When moving back to foreground, the stream becomes active again.
My research showed that Android 9+ has this behavior for apps for security reasons. To prevent this, a FOREGROUND SERVICE must be started for a process, that uses a microphone (with static ongoing notification like "this app is using microphone in background). Have anynody tried this ? I am new to Java and android architecture in general, so any help will be highly appreciated

**Comment by vtn-dev-prithipal** [comment]
@DrSchmurge please use React-native-callkeep plugin to handle this scenario. When you use connectionService from telecom package in Android, it will consider this as a phone call in both foreground and background scenario

https://www.npmjs.com/package/react-native-callkeep

**Comment by DrSchmurge** [comment]
> @DrSchmurge please use React-native-callkeep plugin to handle this scenario. When you use connectionService from telecom package in Android, it will consider this as a phone call in both foreground and background scenario
> 
> https://www.npmjs.com/package/react-native-callkeep

Hello, thanks for your answer,
I recently did exactly this - I installed and configured callkeep, and it is working fine, but two issues are stopping me from using it:
1) I can not make callkeep to show caller name - it shows only the number i pass to it. I opened a corresponding issue recently: https://github.com/react-native-webrtc/react-native-callkeep/issues/187
2) Recent calls show up in native Phone call list UI, and I do not need it, but have no option to change this behaviour.
