### ISSUE TITLE
Getting error  when i make a call 

### ISSUE THREAD

**Issue by lavarajallu** [datso/react-native-pjsip#78]
03-01 11:46:07.178  6701  8391 W ReactNativeJS: Possible Unhandled Promise Rejection (id: 0):
03-01 11:46:07.178  6701  8391 W ReactNativeJS: TypeError: undefined is not an object (evaluating 'account.getRegServer')
03-01 11:46:07.178  6701  8391 W ReactNativeJS: _normalize@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:79119:40
03-01 11:46:07.178  6701  8391 W ReactNativeJS: makeCall@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:78843:46
03-01 11:46:07.178  6701  8391 W ReactNativeJS: makeCallMethod$@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:77312:66
03-01 11:46:07.178  6701  8391 W ReactNativeJS: tryCatch@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14069:23
03-01 11:46:07.178  6701  8391 W ReactNativeJS: invoke@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14242:32
03-01 11:46:07.178  6701  8391 W ReactNativeJS: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14112:30
03-01 11:46:07.178  6701  8391 W ReactNativeJS: tryCatch@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14069:23
03-01 11:46:07.178  6701  8391 W ReactNativeJS: invoke@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14145:30
03-01 11:46:07.178  6701  8391 W ReactNativeJS: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14173:19
03-01 11:46:07.178  6701  8391 W ReactNativeJS: tryCallTwo@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:13407:9
03-01 11:46:07.178  6701  8391 W ReactNativeJS: doResolve@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:13571:25
03-01 11:46:07.178  6701  8391 W ReactNativeJS: Promise@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:13430:14
03-01 11:46:07.178  6701  8391 W ReactNativeJS: callInvokeWithMethodAndArg@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14172:29
03-01 11:46:07.178  6701  8391 W ReactNativeJS: enqueue@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14177:157
03-01 11:46:07.178  6701  8391 W ReactNativeJS: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14112:30
03-01 11:46:07.178  6701  8391 W ReactNativeJS: async@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14193:69
03-01 11:46:07.178  6701  8391 W ReactNativeJS: makeCallMethod@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:77300:40
03-01 11:46:07.178  6701  8391 W ReactNativeJS: proxiedMethod@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:34306:37
03-01 11:46:07.178  6701  8391 W ReactNativeJS: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:77506:32
03-01 11:46:07.178  6701  8391 W ReactNativeJS: commitCallbacks@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:6309:25
03-01 11:46:07.178  6701  8391 W ReactNativeJS: commitLifeCycles@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:8502:34
03-01 11:46:07.178  6701  8391 W ReactNativeJS: commitAllLifeCycles@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:9552:31
03-01 11:46:07.178  6701  8391 W ReactNativeJS: _invokeGuardedCallback@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:2774:21
03-01 11:46:07.178  6701  8391 W ReactNativeJS: invokeGuardedCallback@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:2736:39
03-01 11:46:07.178  6701  8391 W ReactNativeJS: commitRoot@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:9632:38
03-01 11:46:07.178  6701  8391 W ReactNativeJS: completeRoot@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:10524:52
03-01 11:46:07.178  6701  8391 W ReactNativeJS: performWorkOnRoot@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:10481:29
03-01 11:46:07.178  6701  8391 W ReactNativeJS: performWork@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:10415:30
03-01 11:46:07.178  6701  8391 W ReactNativeJS: batchedUpdates@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:10560:26
03-01 11:46:07.178  6701  8391 W ReactNativeJS: batchedUpdates@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:4107:37
03-01 11:46:07.178  6701  8391 W ReactNativeJS: _receiveRootNodeIDEvent@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:4190:23
03-01 11:46:07.178  6701  8391 W ReactNativeJS: receiveTouches@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:4220:34
03-01 11:46:07.178  6701  8391 W ReactNativeJS: __callFunction@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:2361:49
03-01 11:46:07.178  6701  8391 W ReactNativeJS: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:2131:31
03-01 11:46:07.178  6701  8391 W ReactNativeJS: __guardSafe@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:2323:13
03-01 11:46:07.178  6701  8391 W ReactNativeJS: callFunctionReturnFlushedQueue@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:2130:21
03-01 11:46:07.178  6701  8391 W ReactNativeJS: callFunctionReturnFlushedQueue@[native code]
03-01 11:46:08.131  6701  8391 W ReactNativeJS: Possible Unhandled Promise Rejection (id: 1):
03-01 11:46:08.131  6701  8391 W ReactNativeJS: "Title:       pjsua_acc_add(&pj_acc_cfg, make_default, &id)
03-01 11:46:08.131  6701  8391 W ReactNativeJS: Code:        70010
03-01 11:46:08.131  6701  8391 W ReactNativeJS: Description: Too many objects of the specified type (PJ_ETOOMANY)
03-01 11:46:08.131  6701  8391 W ReactNativeJS: Location:    ../src/pjsua2/account.cpp:733
03-01 11:46:08.131  6701  8391 W ReactNativeJS: "
03-01 11:46:09.150  6701  8391 W ReactNativeJS: Possible Unhandled Promise Rejection (id: 2):
03-01 11:46:09.150  6701  8391 W ReactNativeJS: TypeError: undefined is not an object (evaluating 'call.getId')
03-01 11:46:09.150  6701  8391 W ReactNativeJS: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:78871:75
03-01 11:46:09.150  6701  8391 W ReactNativeJS: tryCallTwo@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:13407:9
03-01 11:46:09.150  6701  8391 W ReactNativeJS: doResolve@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:13571:25
03-01 11:46:09.150  6701  8391 W ReactNativeJS: Promise@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:13430:14
03-01 11:46:09.150  6701  8391 W ReactNativeJS: hangupCall@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:78870:35
03-01 11:46:09.150  6701  8391 W ReactNativeJS: hangUpCall$@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:77340:68
03-01 11:46:09.150  6701  8391 W ReactNativeJS: tryCatch@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14069:23
03-01 11:46:09.150  6701  8391 W ReactNativeJS: invoke@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14242:32
03-01 11:46:09.150  6701  8391 W ReactNativeJS: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14112:30
03-01 11:46:09.150  6701  8391 W ReactNativeJS: tryCatch@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14069:23
03-01 11:46:09.150  6701  8391 W ReactNativeJS: invoke@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14145:30
03-01 11:46:09.150  6701  8391 W ReactNativeJS: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14173:19
03-01 11:46:09.150  6701  8391 W ReactNativeJS: tryCallTwo@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:13407:9
03-01 11:46:09.150  6701  8391 W ReactNativeJS: doResolve@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:13571:25
03-01 11:46:09.150  6701  8391 W ReactNativeJS: Promise@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:13430:14
03-01 11:46:09.150  6701  8391 W ReactNativeJS: callInvokeWithMethodAndArg@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14172:29
03-01 11:46:09.150  6701  8391 W ReactNativeJS: enqueue@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14177:157
03-01 11:46:09.150  6701  8391 W ReactNativeJS: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14112:30
03-01 11:46:09.150  6701  8391 W ReactNativeJS: async@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14193:69
03-01 11:46:09.150  6701  8391 W ReactNativeJS: hangUpCall@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:77329:40
03-01 11:46:09.150  6701  8391 W ReactNativeJS: proxiedMethod@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:34306:37
03-01 11:46:09.150  6701  8391 W ReactNativeJS: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:77495:28
03-01 11:46:09.150  6701  8391 W ReactNativeJS: commitCallbacks@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:6309:25
03-01 11:46:09.150  6701  8391 W ReactNativeJS: commitLifeCycles@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:8502:34
03-01 11:46:09.150  6701  8391 W ReactNativeJS: commitAllLifeCycles@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:9552:31
03-01 11:46:09.150  6701  8391 W ReactNativeJS: _invokeGuardedCallback@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:2774:21
03-01 11:46:09.150  6701  8391 W ReactNativeJS: invokeGuardedCallback@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:2736:39
03-01 11:46:09.150  6701  8391 W ReactNativeJS: commitRoot@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:9632:38
03-01 11:46:09.150  6701  8391 W ReactNativeJS: completeRoot@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:10524:52
03-01 11:46:09.150  6701  8391 W ReactNativeJS: performWorkOnRoot@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:10481:29
03-01 11:46:09.150  6701  8391 W ReactNativeJS: performWork@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:10415:30
03-01 11:46:09.150  6701  8391 W ReactNativeJS: batchedUpdates@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:10560:26
03-01 11:46:09.150  6701  8391 W ReactNativeJS: batchedUpdates@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:4107:37
03-01 11:46:09.150  6701  8391 W ReactNativeJS: _receiveRootNodeIDEvent@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:4190:23
03-01 11:46:09.150  6701  8391 W ReactNativeJS: receiveTouches@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:4220:34
03-01 11:46:09.150  6701  8391 W ReactNativeJS: __callFunction@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:2361:49
03-01 11:46:09.150  6701  8391 W ReactNativeJS: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:2131:31
03-01 11:46:09.150  6701  8391 W ReactNativeJS: __guardSafe@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:2323:13
03-01 11:46:09.150  6701  8391 W ReactNativeJS: callFunctionReturnFlushedQueue@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:2130:21
03-01 11:46:09.150  6701  8391 W ReactNativeJS: callFunctionReturnFlushedQueue@[native code]
03-01 11:46:59.923  6701  8391 W ReactNativeJS: Possible Unhandled Promise Rejection (id: 3):
03-01 11:46:59.923  6701  8391 W ReactNativeJS: TypeError: undefined is not an object (evaluating 'account.getRegServer')
03-01 11:46:59.923  6701  8391 W ReactNativeJS: _normalize@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:79119:40
03-01 11:46:59.923  6701  8391 W ReactNativeJS: makeCall@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:78843:46
03-01 11:46:59.923  6701  8391 W ReactNativeJS: makeCallMethod$@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:77312:66
03-01 11:46:59.923  6701  8391 W ReactNativeJS: tryCatch@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14069:23
03-01 11:46:59.923  6701  8391 W ReactNativeJS: invoke@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14242:32
03-01 11:46:59.923  6701  8391 W ReactNativeJS: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14112:30
03-01 11:46:59.923  6701  8391 W ReactNativeJS: tryCatch@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14069:23
03-01 11:46:59.923  6701  8391 W ReactNativeJS: invoke@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14145:30
03-01 11:46:59.923  6701  8391 W ReactNativeJS: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14173:19
03-01 11:46:59.923  6701  8391 W ReactNativeJS: tryCallTwo@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:13407:9
03-01 11:46:59.923  6701  8391 W ReactNativeJS: doResolve@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:13571:25
03-01 11:46:59.923  6701  8391 W ReactNativeJS: Promise@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:13430:14
03-01 11:46:59.923  6701  8391 W ReactNativeJS: callInvokeWithMethodAndArg@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14172:29
03-01 11:46:59.923  6701  8391 W ReactNativeJS: enqueue@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14177:157
03-01 11:46:59.923  6701  8391 W ReactNativeJS: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14112:30
03-01 11:46:59.923  6701  8391 W ReactNativeJS: async@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14193:69
03-01 11:46:59.923  6701  8391 W ReactNativeJS: makeCallMethod@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:77300:40
03-01 11:46:59.923  6701  8391 W ReactNativeJS: proxiedMethod@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:34306:37
03-01 11:46:59.923  6701  8391 W ReactNativeJS: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:77506:32
03-01 11:46:59.923  6701  8391 W ReactNativeJS: commitCallbacks@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:6309:25
03-01 11:46:59.923  6701  8391 W ReactNativeJS: commitLifeCycles@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:8502:34
03-01 11:46:59.923  6701  8391 W ReactNativeJS: commitAllLifeCycles@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:9552:31
03-01 11:46:59.923  6701  8391 W ReactNativeJS: _invokeGuardedCallback@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:2774:21
03-01 11:46:59.923  6701  8391 W ReactNativeJS: invokeGuardedCallback@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:2736:39
03-01 11:46:59.923  6701  8391 W ReactNativeJS: commitRoot@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:9632:38
03-01 11:46:59.923  6701  8391 W ReactNativeJS: completeRoot@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:10524:52
03-01 11:46:59.923  6701  8391 W ReactNativeJS: performWorkOnRoot@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:10481:29
03-01 11:46:59.923  6701  8391 W ReactNativeJS: performWork@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:10415:30
03-01 11:46:59.923  6701  8391 W ReactNativeJS: batchedUpdates@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:10560:26
03-01 11:46:59.923  6701  8391 W ReactNativeJS: batchedUpdates@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:4107:37
03-01 11:46:59.923  6701  8391 W ReactNativeJS: _receiveRootNodeIDEvent@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:4190:23
03-01 11:46:59.923  6701  8391 W ReactNativeJS: receiveTouches@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:4220:34
03-01 11:46:59.923  6701  8391 W ReactNativeJS: __callFunction@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:2361:49
03-01 11:46:59.923  6701  8391 W ReactNativeJS: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:2131:31
03-01 11:46:59.923  6701  8391 W ReactNativeJS: __guardSafe@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:2323:13
03-01 11:46:59.923  6701  8391 W ReactNativeJS: callFunctionReturnFlushedQueue@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:2130:21
03-01 11:46:59.923  6701  8391 W ReactNativeJS: callFunctionReturnFlushedQueue@[native code]
03-01 11:47:05.498  6701  8391 W ReactNativeJS: Possible Unhandled Promise Rejection (id: 4):
03-01 11:47:05.498  6701  8391 W ReactNativeJS: TypeError: undefined is not an object (evaluating 'call.getId')
03-01 11:47:05.498  6701  8391 W ReactNativeJS: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:78871:75
03-01 11:47:05.498  6701  8391 W ReactNativeJS: tryCallTwo@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:13407:9
03-01 11:47:05.498  6701  8391 W ReactNativeJS: doResolve@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:13571:25
03-01 11:47:05.498  6701  8391 W ReactNativeJS: Promise@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:13430:14
03-01 11:47:05.498  6701  8391 W ReactNativeJS: hangupCall@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:78870:35
03-01 11:47:05.498  6701  8391 W ReactNativeJS: hangUpCall$@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:77340:68
03-01 11:47:05.498  6701  8391 W ReactNativeJS: tryCatch@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14069:23
03-01 11:47:05.498  6701  8391 W ReactNativeJS: invoke@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14242:32
03-01 11:47:05.498  6701  8391 W ReactNativeJS: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14112:30
03-01 11:47:05.498  6701  8391 W ReactNativeJS: tryCatch@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14069:23
03-01 11:47:05.498  6701  8391 W ReactNativeJS: invoke@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14145:30
03-01 11:47:05.498  6701  8391 W ReactNativeJS: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14173:19
03-01 11:47:05.498  6701  8391 W ReactNativeJS: tryCallTwo@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:13407:9
03-01 11:47:05.498  6701  8391 W ReactNativeJS: doResolve@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:13571:25
03-01 11:47:05.498  6701  8391 W ReactNativeJS: Promise@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:13430:14
03-01 11:47:05.498  6701  8391 W ReactNativeJS: callInvokeWithMethodAndArg@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14172:29
03-01 11:47:05.498  6701  8391 W ReactNativeJS: enqueue@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14177:157
03-01 11:47:05.498  6701  8391 W ReactNativeJS: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14112:30
03-01 11:47:05.498  6701  8391 W ReactNativeJS: async@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:14193:69
03-01 11:47:05.498  6701  8391 W ReactNativeJS: hangUpCall@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:77329:40
03-01 11:47:05.498  6701  8391 W ReactNativeJS: proxiedMethod@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:34306:37
03-01 11:47:05.498  6701  8391 W ReactNativeJS: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:77495:28
03-01 11:47:05.498  6701  8391 W ReactNativeJS: commitCallbacks@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:6309:25
03-01 11:47:05.498  6701  8391 W ReactNativeJS: commitLifeCycles@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:8502:34
03-01 11:47:05.498  6701  8391 W ReactNativeJS: commitAllLifeCycles@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:9552:31
03-01 11:47:05.498  6701  8391 W ReactNativeJS: _invokeGuardedCallback@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:2774:21
03-01 11:47:05.498  6701  8391 W ReactNativeJS: invokeGuardedCallback@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:2736:39
03-01 11:47:05.498  6701  8391 W ReactNativeJS: commitRoot@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:9632:38
03-01 11:47:05.498  6701  8391 W ReactNativeJS: completeRoot@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:10524:52
03-01 11:47:05.498  6701  8391 W ReactNativeJS: performWorkOnRoot@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:10481:29
03-01 11:47:05.498  6701  8391 W ReactNativeJS: performWork@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:10415:30
03-01 11:47:05.498  6701  8391 W ReactNativeJS: batchedUpdates@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:10560:26
03-01 11:47:05.498  6701  8391 W ReactNativeJS: batchedUpdates@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:4107:37
03-01 11:47:05.498  6701  8391 W ReactNativeJS: _receiveRootNodeIDEvent@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:4190:23
03-01 11:47:05.498  6701  8391 W ReactNativeJS: receiveTouches@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:4220:34
03-01 11:47:05.498  6701  8391 W ReactNativeJS: __callFunction@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:2361:49
03-01 11:47:05.498  6701  8391 W ReactNativeJS: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:2131:31
03-01 11:47:05.498  6701  8391 W ReactNativeJS: __guardSafe@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:2323:13
03-01 11:47:05.498  6701  8391 W ReactNativeJS: callFunctionReturnFlushedQueue@http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:2130:21
03-01 11:47:05.498  6701  8391 W ReactNativeJS: callFunctionReturnFlushedQueue@[native code]

**Comment by datso** [comment]
Hey, pjsip has limited number of active accounts that could be created. When you are trying to create more then expected, you will get the error - remove the redundant accounts that was created previously.

> Description: Too many objects of the specified type (PJ_ETOOMANY)

**Comment by lavarajallu** [comment]
Okay than for your response ..But I called in will mount. When I was run
the application every time it will be created account. So how can I remove
this??

**Comment by datso** [comment]
You should compare the existing accounts in the service in PjSipEndpoint.start method, and create it only when account doesn't exist. 
ComponentWillMount could be called many times for the same service instance.

**Comment by lavarajallu** [comment]
can you please show me the sample  how can i fix this one

**Comment by lavarajallu** [comment]
componentWillMount() {  // this is one of the component Life-Cycle
method. This is method calling when user comes this Page  Account created
automatically....
       this.getServerDetails()
    }




    async  getServerDetails() {  // This is User Details getting by fetch
Method in react-native
     try {
           let response = await fetch(serverUrl);
            let responseJson = await response.json();

            var getAccountValues = {   // now i created one Object getting
details from  service what i need that details should pass to Object.
                    name: responseJson.SipServerSettings.DisplayName,
                    username:
responseJson.SipServerSettings.PrivateIdentity,
                    domain: responseJson.SipServerSettings.Realm,
                    password: responseJson.SipServerSettings.Password
                   // UDP: responseJson.SipServerSettings.SIPUDP    // here
if you want server Host or Udp just pass waht you need like this present
now i am not passing
                  }

                    const endpoint = new Endpoint();  // this is EndPoint
Object from getting resources . this endPoint based on working entire App...
                    endpoint.start().then((state) => {
                     endpoint.createAccount(getAccountValues).then
                     ((account) => {
                         console.log("Your account", account)
                          userAccount = account
                    })
                  })

       } catch (error) {
        console.error(error);
      }
    }


This is my code ,

where i am using add Event listner methods and how can i use timer whe
nuser pickup the call please suggest

every time create account how can i solve this issue

**Comment by lavarajallu** [comment]
Please give me suggestion how can i resolve this one and how can i put
timer when other person pickup call and  how can i use addEvent listeners
