### ISSUE TITLE
Cannot place incoming call on hold

### ISSUE THREAD

**Issue by mattyleggy** [datso/react-native-pjsip#84]
Cannot place an incoming call on hold as it says: `Call/Transaction Does Not Exist`. Does this on both Android and iOS. Works fine for outbound calls.

**Comment by datso** [comment]
Hey, could you please attach the SIP trace ? (tcpdump, or logs from `adb logcat | grep PjSip`)

**Comment by mattyleggy** [comment]
@datso - Here's the log from `adb logcat | grep PjSip` when placing a call on hold and it failing.
[logs2.txt](https://github.com/datso/react-native-pjsip/files/1817412/logs2.txt)

**Comment by datso** [comment]
Thanks, for the logs. Could you please comment the transports creation for TCP / TLS, and try again.
```
{
                TransportConfig transportConfig = new TransportConfig();
                transportConfig.setQosType(pj_qos_type.PJ_QOS_TYPE_VOICE);
                mTcpTransportId = mEndpoint.transportCreate(pjsip_transport_type_e.PJSIP_TRANSPORT_TCP, transportConfig);
                mTrash.add(transportConfig);
            }
            {
                TransportConfig transportConfig = new TransportConfig();
                transportConfig.setQosType(pj_qos_type.PJ_QOS_TYPE_VOICE);
                mTlsTransportId = mEndpoint.transportCreate(pjsip_transport_type_e.PJSIP_TRANSPORT_TLS, transportConfig);
                mTrash.add(transportConfig);
            }
```

**Comment by mattyleggy** [comment]
@datso - Where should that be added?

**Comment by iBuntaah** [comment]
@mattyleggy I think its in the PjSipService class from yourProject/node_modules/react-native-pjsip/android/src/main/java/com/carusto/ReactNativePjSip/PjSipService.java

**Comment by mattyleggy** [comment]
@datso - Thanks for the suggestions however commenting these out had made no difference. Any other ideas that I could try?

@iBuntaah - Thanks for pointing me to the correct location.
