### ISSUE TITLE
Can't hear anymore after unholding a call

### ISSUE THREAD

**Issue by iBuntaah** [datso/react-native-pjsip#88]
Hi,

I have a problem when I put a call on hold then I unhold it.
Device A calls me, I answered, put the call in hold then unhold it. The device A can hear me but I can't hear it anymore.

I answered the call: 
"status":"PJSUA_CALL_MEDIA_ACTIVE"
"type": "PJMEDIA_TYPE_AUDIO",
"dir": "PJMEDIA_DIR_ENCODING_DECODING"

I put the call on hold: 
"status":"PJSUA_CALL_MEDIA_LOCAL_HOLD",
 "type": "PJMEDIA_TYPE_AUDIO",
"dir": "PJMEDIA_DIR_ENCODING"

Unhold the call :  
"status": "PJSUA_CALL_MEDIA_NONE",
"type": "PJMEDIA_TYPE_VIDEO",
"dir": "PJMEDIA_DIR_NONE"

Any help would be appreciated, thanks

**Comment by mattyleggy** [comment]
Is this on iOS or Android?

**Comment by mattyleggy** [comment]
It could have something to do with the React Native PjSip upgrade to 2.7.1.
You could try downgrading the module to 2.7.0 and see if that makes any
difference.

**Comment by iBuntaah** [comment]
After npm remove then npm install, It appears that I can't make or receive calls from the 2.7.0 and the 2.7.1 version of react-native-pjsip. The 2.7.2 didn't compile (error: package org.pjsip.pjsua2 does not exist).

However, the 2.7.3 and the 2.7.4 version works. But same problem, I can't hear after unholding a call.

**Comment by iBuntaah** [comment]
Update: 
I found that it only happens with opus codec and only for incoming calls
