### ISSUE TITLE
please clarify what's needed to complete ios support

### ISSUE THREAD

**Issue by sneerin** [datso/react-native-pjsip#9]
I saw some code in ios folder, can you please describe what do I need to integrate ios

**Comment by datso** [comment]
Hello, iOS version not ready yet.
But you can contribute, currently, I don't have time to proceed on iOS.

**Comment by iclems** [comment]
+1 Any list of what's left to do? I've worked on Mac with PJSIP in other contexts and it shouldn't take long to reach feature parity with Android.

**Comment by datso** [comment]
Hi, going to proceed on iOS version this week.

**Comment by iclems** [comment]
Oh awesome. Let me know if you need help. FYI, I've been inspired in the past by the source of this (open source) app implementation of PJSIP on Mac: https://github.com/64characters/Telephone
