### ISSUE TITLE
None of the subscribe events got called to the caller when the receiver rejects the call.

### ISSUE THREAD

**Issue by basheerkohli** [datso/react-native-pjsip#90]
Hey Team,

In my application when the caller makes a call to some x person (here say receiver person). When the receiver person rejects the call with out taking it .In this scenario none of the events got called in the callers application , if this is happens i can update the view of callers screen status with updated call status like call ended. But this is not happening in my case. Please do support.

Listneres implemented in code are 

                                `endpoint.on("registration_changed", (account) => {
                                    this.setState({inCallText: 'Registering...'})
                                  });
                                endpoint.on("connectivity_changed", (online) => {
                                   this.setState({inCallText: 'Connecting...'})
                                 });
                                endpoint.on("message_received", (call) => {
                                   this.setState({inCallText: 'Message Received...'})
                                 });
                                endpoint.on("call_received", (call) => {
                                    console.log('call info status'+call._stateText);
                                });
                                 endpoint.on("call_changed", (call) => {  //neither this is called when receiver rejects 
                                  console.log('status of the call'+call._stateText);
                                  if(call._stateText === "EARLY"){
                                    this.setState({inCallText:"ringing"})
                                  }
                                   else if(call._stateText === "CONFIRMED" || call._stateText === "CONNECTING"){
                                    this.setState({inCallText:"In call"})
                                  }
                               });
                                   endpoint.on("call_terminated", (call) => {//nor this listener called
                                    console.log('call info status'+call._stateText);
                                });`

**Comment by ryanmcclure4** [comment]
@basheerkohli Were you ever able to figure this out? I'm running into the same issue; the **call_terminated** event is not triggered when the receiver ends or rejects the call from their end

**Comment by dariomalfatti-centropaghe** [comment]
Has anyone figured out how to solve this issue? I'm stuck with that, I got fired the call_changed event with status PJSIP_INV_STATE_CONFIRMED as if the receiver had answer the call.
