### ISSUE TITLE
Does react-native-pjsip support media transport like srtp/zrtp?

### ISSUE THREAD

**Issue by shaydvir** [datso/react-native-pjsip#93]

**Comment by cmendes0101** [comment]
No, it does not right now.

**Comment by shaydvir** [comment]
@cmendes0101 hi, i'm trying to enable the SRTP, i've added these 2 lines to the function "doAccountCreate", in the PjSipService file:
`cfg.getMediaConfig().setSrtpUse(pjmedia_srtp_use.PJMEDIA_SRTP_MANDATORY);
cfg.getMediaConfig().setSrtpSecureSignaling(0);`
in the PBX server it seems to work, i mean the extension is registered succesfuly, and when i'm having a call, it's initated successfuly, but i can't hear the other side, and he can't hear me.
What surprises me is that when on TLS only, it works perfect, only when i add the SRTP it doesn't.

any idea how do i progress from here? any leads?

**Comment by cmendes0101** [comment]
Sorry I cannot help. I replied and said it was not supported in this package which i believe is still the case.

Looks like you just want to get PJSIP SRTP to work outside of this package. If so please go to the PJSIP community for help on troubleshooting.

**Comment by shaydvir** [comment]
I fiex this issue by downgrading the pjsip version to 2.6
